baseURL = 'https://mansona.tech/'
languageCode = 'en-us'
title = 'Hilman Mustofa | Blog'
theme = 'hugo-blog-awesome'

enableEmoji = true

googleAnalytics = ''

[params]
  goToTop = true

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next line
disqusShortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Hilman Mustofa"
  defaultColor = "dark" # set default color mode: dark or light
  description = "Blog posts and more."

[params.author]
  #avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Hilman's Journal"
  name = "Hilman Mustofa"
  description = "Hi, I am Hilman👋. This blog is created to share my professional experience as Cloud Engineer."

[[params.socialIcons]]
name = "github"
url = "https://github.com/hilmanmustofaa"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/hilmanmustofa/"

[[params.socialIcons]]
name = "Rss"
url = "../index.xml"